apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
